### ISSUE TITLE
Does not clean up after failing tests

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry-incubator/cf-openstack-validator#17]
When the tests run without issues, cf-openstack-validator cleans up OpenStack properly, but if some tests fail, at least in the early stages, the vms, volumes and similar do not get cleaned up so they accumulate over time.

We had this issue with version 2.4 and also with the latest 2.5.

It should be quite easy to reproduce by letting some tests fail. If not I will debug it further if this happens only for some failures.

**Comment by voelzmo** [comment]
Thanks @thardeck,

we should have coding in place to specifically avoid this: https://github.com/cloudfoundry-incubator/cf-openstack-validator/blob/master/lib/validator/api/resource_tracker.rb

If you can provide more information which tests leave resources behind, this would be very helpful. A stacktracke/an error message is also appreciated.

Thanks!

**Comment by thardeck** [comment]
This is the output when the path to the cpi.json is wrong. The log is longer but it repeats itself basically.

The vm `7a1819c1-6001-4804-8604-70f1a32e78a6` is not cleaned up in this case.

```
Your OpenStack
  API
    rate limit
      is high enough... passed
    Security groups
      has ingress rule for SSH... passed
      has egress rule for HTTP... passed
      has egress rule for DNS... passed
  using the CPI
    verifying that the CPI is executable... failed
    against OpenStack
      can save a stemcell... failed
      can create a VM... skipped: No stemcell available
      has VM cid... skipped: No VM to check
      can set VM metadata... skipped: No VM to set metadata for
      can create a disk in same AZ as VM... skipped: No VM to create disk for
      has disk cid... skipped: No disk to check
      can set disk metadata... skipped: No disk to check
      can attach the disk to the VM... skipped: No VM to attach disk to
      can detach the disk from the VM... skipped: No VM to detach disk from
      can take a snapshot... skipped: No disk to create snapshot from
      can delete a snapshot... skipped: No snapshot to delete
      can delete the disk... skipped: No disk to delete
      can delete the VM... skipped: No vm to delete
      can attach floating IP to a VM... skipped: No stemcell to create VM from
      can SSH into VM... skipped: No VM to use
      can access the internet... skipped: No VM to use
      can save and retrieve user-data from metadata service... skipped: No VM to use
      can save and retrieve user-data from config_drive... skipped: `config_drive` is not configured in validator.yml.
      allows a VM to reach the configured NTP server... skipped: No VM to use
      allows one VM to reach port 22 of another VM within the same network... skipped: No VM to use
      can create a VM with static IP... skipped: No stemcell to create VM from
      allows one VM to reach port 22 of another VM with static IP within the same network... skipped: No VM with floating IP to use
      can create large disk... failed
      can delete large disk... skipped: No large disk to delete
      has configured MTU size... skipped: No VM with floating IP to use
      can delete a stemcell... skipped: No stemcell to delete

Failures:

  1) Your OpenStack using the CPI verifying that the CPI is executable
     CPI could not be called OpenStack error: Invalid CPI response - ParserError - 751: unexpected token at 'bundler: failed to load command: /usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi (/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi)
     '

  2) Your OpenStack using the CPI against OpenStack can save a stemcell
     Stemcell could not be uploaded OpenStack error: Invalid CPI response - ParserError - 751: unexpected token at 'bundler: failed to load command: /usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi (/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi)
     '

  3) Your OpenStack using the CPI against OpenStack can create large disk
     Large disk could not be created.
     Hint: If you are using DevStack, you need to manually set a larger backing file size in your localrc. OpenStack error: Invalid CPI response - ParserError - 751: unexpected token at 'bundler: failed to load command: /usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi (/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi)
     '


Finished in 1 minute 10.17 seconds (files took 0.39732 seconds to load)
31 examples, 3 failures, 24 pending
Resources: The following resources might not have been cleaned up:
  VMs:
    - Name: validator-test-vm
      UUID: 7a1819c1-6001-4804-8604-70f1a32e78a6
      Created by test: Your OpenStack API rate limit is high enough

You can find more information in the logs at /root/.cf-openstack-validator/logs/testsuite.log

Error: Running 'RSpec::Core::Runner.run' with arguments '["--order", "defined", "--color", "--tty", "--require", "/usr/lib64/cf-openstack-validator/lib/validator/formatter.rb", "--format", "Validator::TestsuiteFormatter", "src/specs/cpi_lifecycle_spec.rb", "src/specs/extension_spec.rb", "src/specs/openstack_api_spec.rb", "src/specs/spec_helper.rb"]' failed

More details can be found in /root/.cf-openstack-validator/logs/testsuite.log
testsuite.log output:
D, [2017-11-14T17:10:31.750514 #17] DEBUG -- : External CPI sending request: {"method":"info","arguments":[],"context":{"director_uuid":"validator","request_id":"614262"}} with command: /usr/bin/bosh_openstack_cpi
D, [2017-11-14T17:10:32.577619 #17] DEBUG -- : External CPI got response: bundler: failed to load command: /usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi (/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi)
, err: Errno::ENOENT: No such file or directory @ rb_sysopen - /root/.cf-openstack-validator/cpi.json
  /usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/2.4.0/psych.rb:472:in `initialize'
  /usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/2.4.0/psych.rb:472:in `open'
  /usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/2.4.0/psych.rb:472:in `load_file'
  /usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi:9:in `<top (required)>'
, exit_status: pid 25 exit 1
```

**Comment by thardeck** [comment]
I think the cleanup with 2.4 failed when we accidentally were using the new bosh-openstack-cpi which volume api was different so the volume related tests failed.

**Comment by voelzmo** [comment]
The CPI needs its configuration to clean up the VM. In these cases, you indeed end up with resources in your IaaS. At least the validator tells you that this is the case:
```

**Comment by mauromorales** [comment]
Closing since this has been quiet for a while and we need the config to do the cleanup. Feel free to re-open if there is something else that needs to be discussed on this issue.
